# Generated by Django 2.2.7 on 2019-12-02 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='find',
            new_name='How_Did_You_Find_Us',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='line',
            new_name='Leave_us_a_line',
        ),
    ]
