# Generated by Django 2.2.7 on 2019-12-01 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('price', models.TextField()),
                ('per', models.TextField()),
                ('adv1', models.TextField()),
                ('adv2', models.TextField()),
                ('adv3', models.TextField()),
                ('adv4', models.TextField()),
            ],
        ),
    ]
