# Generated by Django 2.2.7 on 2019-12-02 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191202_0429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='places',
            name='random',
        ),
    ]
