# Generated by Django 2.2.7 on 2019-12-02 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20191202_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='places',
            name='seats',
        ),
    ]
